
\pagenumbering{roman}

# Forord (**WIP DO NOT CITE ANY CONTENT**) {-}

Bogen er baseret på forskningsprojektet *”Measuring intense migrant-native contact and its concequences”* (MNcontact), der var finansieret af Den Fri Forskningsfond i perioden fra 2019 til 2024. Bogen er en formidlingsbog, der er baseret på projektets datamateriale og forskningsresultater. 

Projektgruppen har bestået af undertegnet, [Jeppe Fjeldgaard Larsen](https://vbn.aau.dk/da/persons/jeppefl), [Lanciné Eric Diop-Christensen](https://vbn.aau.dk/en/persons/led), [Hans-Peter Y. Qvist](https://vbn.aau.dk/da/persons/hpq), [Jeevitha Y. Qvist](https://vbn.aau.dk/en/persons/jy), [Troels Fage Hedegaard](https://vbn.aau.dk/en/persons/troelsfh) og [Anna Diop-Christensen](https://dk.linkedin.com/in/anna-diop-christensen-58b5ba282) (i tilfældig rækkefølje). Gruppen har i forskellige konstellationer publiceret en række videnskabelige publikationer og flere er på vej. De er samlet på [projektets hjemmeside](https://vbn.aau.dk/en/projects/measuring-intense-migrant-native-contact-and-its-consequences/publications/). 

Undervejs har vi arbejdet tæt sammen [Anders Bastrup Jørgensen]( https://vbn.aau.dk/en/persons/anbajo), der skrev Ph.D-afhandling om indvandrere og efterkommeres deltagelse i frivillige foreninger. Vi har også arbejdet sammen med [Rolf Lyneborg Lund]( https://vbn.aau.dk/en/persons/rolfll) og [Anja Jørgensen]( https://vbn.aau.dk/en/persons/anjaj), der i samme periode analyserede spørgsmålet om indvandrere- og efterkommeres boligmæssige placering. 

Vi ønsker alle en god læselyst 

Aalborg 2024


[Christian Albrekt Larsen](https://vbn.aau.dk/en/persons/albrekt)


Forskningsleder på MNcontact. \
Professor, Institut for Politik og Samfund\
Aalborg Universitet\

\newpage

ISSN: xxxx-xxxx      
ISBN: xxx-xx-xxxx-xxx-x    
       
Published by:  
Aalborg University Press  
Skjernvej 4A, 2nd floor    
DK – 9220 Aalborg Ø     
Phone: +45 99407140   
aauf@forlag.aau.dk     
forlag.aau.dk      

© Copyright by author(s)

\newpage

```{=latex}
\tableofcontents
```
